<?php require './templates/header.phtml'; ?>
<div class="p-3 mb-auto bg-secondary text-white" style="width: 100%;">
<br>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Titulo</th>
                <th scope="col">Fecha de lanzamiento</th>
                <th scope="col">Director</th>
                <th scope="col">Sinopsis</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($peliculas as $pelicula) : ?>
                <tr>
                    <th scope="row"><?= $pelicula->id_pelicula ?></th>
                    <td><?= $pelicula->Titulo ?></td>
                    <td><?= $pelicula->{'FechaDeLanzamiento'} ?></td>
                    <td><?= $pelicula->Director ?></td>
                    <td><?= $pelicula->Sinopsis; ?></td>
                    <td><a href="listar"><button class="btn btn-warning">Volver</button></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php require './templates/footer.phtml'; ?>
