<?php
$peliculasHTML = ''; // Variable para almacenar el HTML de las películas
        $peliculasHTML .= "<div class='pelicula-item'>";
        $peliculasHTML .= "<h3>" . $row['pelicula_titulo'] . "</h3>";
        $peliculasHTML .= "<p><strong>Director:</strong> " . $row['Director'] . "</p>";
        $peliculasHTML .= "<p><strong>Fecha de lanzamiento:</strong> " . $row['Fecha de lanzamiento'] . "</p>";
        $peliculasHTML .= "<p><strong>Sinopsis:</strong> " . $row['Sinopsis'] . "</p>";
        $peliculasHTML .= "<p><strong>Género:</strong> " . $row['Genero'] . "</p>";
        $peliculasHTML .= "</div>";   
?>
    