<?php require './templates/header.phtml'; ?>
<?php require './templates/peliculaabm.phtml'; ?>
<div class="p-3 mb-auto bg-secondary text-white" style="width: 100%; height: 450px">
<table class="table table-dark">
    <h1 class="display-4">Lista de Peliculas</h1>
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Pelicula</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <?php foreach ($peliculas as $pelicula) : ?>
        <tbody>
            <tr>
                <th scope="row"><?= $pelicula->id_pelicula ?></th>
                <td><?= $pelicula->Titulo ?></td>
                <td><a href="details/<?= $pelicula->id_pelicula ?> "><button class="btn btn-primary">Ver Más</button></a> 
                <?php if (AuthHelper::verify()) : ?> 
                    <a href="delete/<?= $pelicula->id_pelicula ?> "><button class="btn btn-danger ms-5">Borrar</button></a></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
        </tbody>
</table>
</div>
<?php require './templates/footer.phtml'; ?>