<?php require 'templates/header.phtml'; ?>

<div class="container">
    <h2>Listado de Películas</h2>
    <p>Categorías</p>
    <form method="GET" action="<?= BASE_URL ?>listar">
        <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="categoria">
            <option value=""></option>
            <?php
            // Obtener las categorías de la base de datos y llenar el select
            try {
                $db = new PDO('mysql:host=localhost;dbname=db_peliculas;charset=utf8mb4', 'root', '');

                $query = "SELECT * FROM genero";

                $stmt = $db->prepare($query);
                $stmt->execute();

                if ($stmt->rowCount() > 0) {
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        echo "<option value='" . $row['id_genero'] . "'>" . $row['nombre'] . "</option>";
                    }
                } else {
                    echo "<option value=''>No hay categorías disponibles</option>";
                }
            } catch (PDOException $e) {
                echo "Error: " . $e->getMessage();
            }
            ?>
        </select>
        <button type="submit">Filtrar</button>
    </form>

    <div class="pelicula-list">
        <?php
        try {
            $db = new PDO('mysql:host=localhost;dbname=db_peliculas;charset=utf8mb4', 'root', '');
            $categoriaSeleccionada = isset($_GET['categoria']) ? $_GET['categoria'] : null;

            $query = "SELECT Titulo AS pelicula_titulo, Director, `Fecha de lanzamiento`, Sinopsis, g.nombre AS Genero
          FROM pelicula p
          JOIN genero g ON p.id_genero = g.id_genero";

            if ($categoriaSeleccionada) {
                // Modifica la consulta para incluir la condición del género seleccionado
                $query .= " WHERE p.id_genero = :id_genero";

                $stmt = $db->prepare($query);
                $stmt->bindParam(':id_genero', $categoriaSeleccionada, PDO::PARAM_INT);
            } else {
                $stmt = $db->prepare($query);
            }

            $stmt->execute();

            $peliculasHTML = ''; // Variable para almacenar el HTML de las películas

            if ($stmt->rowCount() > 0) {
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    require_once 'templates/itemPelicula.phtml';
                }
            } else {
                $peliculasHTML = "<p>No se encontraron películas.</p>";
            }

            // Imprimir el HTML de las películas
            echo $peliculasHTML;

            $db = null;
        } catch (PDOException $e) {
            echo "Error: " . $e->getMessage();
        }
        ?>
    </div>
</div>

<?php require 'templates/footer.phtml'; ?>
